### ISSUE TITLE
Se necesita aclaracion sobre la entidad que representa a capataces y su relacion con obras.

### ISSUE THREAD

**Issue by leondominguez** [Blessed0314/ConstructoraBobDS1#2]
se requiere saber si la relacion entre capataces y obras sera una relacion 1 a muchos o muchos a muchos.

**Comment by Blessed0314** [comment]
Será de muchos a muchos, se manejará en la tabla intermedia de asignación
obra

**Comment by Blessed0314** [comment]
Ya quedo aclarado.
